
package https.webservices_sabre_com.websvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EndTransactionService", targetNamespace = "https://webservices.sabre.com/websvc", wsdlLocation = "http://webservices.sabre.com/wsdl/tpfc/EndTransactionLLS2.0.4RQ.wsdl")
public class EndTransactionService
    extends Service
{

    private final static URL ENDTRANSACTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENDTRANSACTIONSERVICE_EXCEPTION;
    private final static QName ENDTRANSACTIONSERVICE_QNAME = new QName("https://webservices.sabre.com/websvc", "EndTransactionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.sabre.com/wsdl/tpfc/EndTransactionLLS2.0.4RQ.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENDTRANSACTIONSERVICE_WSDL_LOCATION = url;
        ENDTRANSACTIONSERVICE_EXCEPTION = e;
    }

    public EndTransactionService() {
        super(__getWsdlLocation(), ENDTRANSACTIONSERVICE_QNAME);
    }

    public EndTransactionService(URL wsdlLocation) {
        super(wsdlLocation, ENDTRANSACTIONSERVICE_QNAME);
    }

    public EndTransactionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns EndTransactionPortType
     */
    @WebEndpoint(name = "EndTransactionPortType")
    public EndTransactionPortType getEndTransactionPortType() {
        return super.getPort(new QName("https://webservices.sabre.com/websvc", "EndTransactionPortType"), EndTransactionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndTransactionPortType
     */
    @WebEndpoint(name = "EndTransactionPortType")
    public EndTransactionPortType getEndTransactionPortType(WebServiceFeature... features) {
        return super.getPort(new QName("https://webservices.sabre.com/websvc", "EndTransactionPortType"), EndTransactionPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENDTRANSACTIONSERVICE_EXCEPTION!= null) {
            throw ENDTRANSACTIONSERVICE_EXCEPTION;
        }
        return ENDTRANSACTIONSERVICE_WSDL_LOCATION;
    }

}
