
package https.webservices_sabre_com.websvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import com.sabre.webservices.sabrexml._2011._10.EndTransactionRQ;
import com.sabre.webservices.sabrexml._2011._10.EndTransactionRS;
import org.ebxml.namespaces.messageheader.MessageHeader;
import org.xmlsoap.schemas.ws._2002._12.secext.Security;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EndTransactionPortType", targetNamespace = "https://webservices.sabre.com/websvc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.sabre.webservices.sabrexml._2011._10.ObjectFactory.class,
    org.xmlsoap.schemas.ws._2002._12.secext.ObjectFactory.class,
    com.sabre.services.stl.v01.ObjectFactory.class,
    com.sabre.services.stl_header.v120.ObjectFactory.class,
    org.ebxml.namespaces.messageheader.ObjectFactory.class,
    org.w3._2000._09.xmldsig.ObjectFactory.class,
    org.xmlsoap.schemas.soap.envelope.ObjectFactory.class
})
public interface EndTransactionPortType {


    /**
     * 
     * @param header2
     * @param header
     * @param body
     * @return
     *     returns com.sabre.webservices.sabrexml._2011._10.EndTransactionRS
     */
    @WebMethod(operationName = "EndTransactionRQ", action = "EndTransactionLLSRQ")
    @WebResult(name = "EndTransactionRS", targetNamespace = "http://webservices.sabre.com/sabreXML/2011/10", partName = "body")
    public EndTransactionRS endTransactionRQ(
        @WebParam(name = "MessageHeader", targetNamespace = "http://www.ebxml.org/namespaces/messageHeader", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<MessageHeader> header,
        @WebParam(name = "Security", targetNamespace = "http://schemas.xmlsoap.org/ws/2002/12/secext", header = true, mode = WebParam.Mode.INOUT, partName = "header2")
        Holder<Security> header2,
        @WebParam(name = "EndTransactionRQ", targetNamespace = "http://webservices.sabre.com/sabreXML/2011/10", partName = "body")
        EndTransactionRQ body);

}
