
package https.webservices_sabre_com.websvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SessionValidateRQService", targetNamespace = "https://webservices.sabre.com/websvc", wsdlLocation = "http://webservices.sabre.com/wsdl/sabreXML1.0.00/usg/SessionValidateRQ.wsdl")
public class SessionValidateRQService
    extends Service
{

    private final static URL SESSIONVALIDATERQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SESSIONVALIDATERQSERVICE_EXCEPTION;
    private final static QName SESSIONVALIDATERQSERVICE_QNAME = new QName("https://webservices.sabre.com/websvc", "SessionValidateRQService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.sabre.com/wsdl/sabreXML1.0.00/usg/SessionValidateRQ.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SESSIONVALIDATERQSERVICE_WSDL_LOCATION = url;
        SESSIONVALIDATERQSERVICE_EXCEPTION = e;
    }

    public SessionValidateRQService() {
        super(__getWsdlLocation(), SESSIONVALIDATERQSERVICE_QNAME);
    }

    public SessionValidateRQService(URL wsdlLocation) {
        super(wsdlLocation, SESSIONVALIDATERQSERVICE_QNAME);
    }

    public SessionValidateRQService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SessionValidatePortType
     */
    @WebEndpoint(name = "SessionValidatePortType")
    public SessionValidatePortType getSessionValidatePortType() {
        return super.getPort(new QName("https://webservices.sabre.com/websvc", "SessionValidatePortType"), SessionValidatePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionValidatePortType
     */
    @WebEndpoint(name = "SessionValidatePortType")
    public SessionValidatePortType getSessionValidatePortType(WebServiceFeature... features) {
        return super.getPort(new QName("https://webservices.sabre.com/websvc", "SessionValidatePortType"), SessionValidatePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SESSIONVALIDATERQSERVICE_EXCEPTION!= null) {
            throw SESSIONVALIDATERQSERVICE_EXCEPTION;
        }
        return SESSIONVALIDATERQSERVICE_WSDL_LOCATION;
    }

}
