
package https.webservices_sabre_com.websvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TravelItineraryReadService", targetNamespace = "https://webservices.sabre.com/websvc", wsdlLocation = "http://webservices.sabre.com/wsdl/sabreXML1.0.00/pnrservices/TravelItineraryReadRQ3.4.0.wsdl")
public class TravelItineraryReadService
    extends Service
{

    private final static URL TRAVELITINERARYREADSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRAVELITINERARYREADSERVICE_EXCEPTION;
    private final static QName TRAVELITINERARYREADSERVICE_QNAME = new QName("https://webservices.sabre.com/websvc", "TravelItineraryReadService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.sabre.com/wsdl/sabreXML1.0.00/pnrservices/TravelItineraryReadRQ3.4.0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRAVELITINERARYREADSERVICE_WSDL_LOCATION = url;
        TRAVELITINERARYREADSERVICE_EXCEPTION = e;
    }

    public TravelItineraryReadService() {
        super(__getWsdlLocation(), TRAVELITINERARYREADSERVICE_QNAME);
    }

    public TravelItineraryReadService(URL wsdlLocation) {
        super(wsdlLocation, TRAVELITINERARYREADSERVICE_QNAME);
    }

    public TravelItineraryReadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns TravelItineraryReadPortType
     */
    @WebEndpoint(name = "TravelItineraryReadPortType")
    public TravelItineraryReadPortType getTravelItineraryReadPortType() {
        return super.getPort(new QName("https://webservices.sabre.com/websvc", "TravelItineraryReadPortType"), TravelItineraryReadPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TravelItineraryReadPortType
     */
    @WebEndpoint(name = "TravelItineraryReadPortType")
    public TravelItineraryReadPortType getTravelItineraryReadPortType(WebServiceFeature... features) {
        return super.getPort(new QName("https://webservices.sabre.com/websvc", "TravelItineraryReadPortType"), TravelItineraryReadPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAVELITINERARYREADSERVICE_EXCEPTION!= null) {
            throw TRAVELITINERARYREADSERVICE_EXCEPTION;
        }
        return TRAVELITINERARYREADSERVICE_WSDL_LOCATION;
    }

}
